spring:
  application:
    name: qldp-application

  jpa:
    generate-ddl: false
  datasource:
    url: jdbc:mysql://localhost:3306/qldp?useSSL=false
    username: user
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
      hibernate:
        SQL: DEBUG
